### ISSUE TITLE
Bug: Download failed

### ISSUE THREAD

**Issue by Glaived** [A-tG/VoicemeeterFancyOSD#17]
![image](https://user-images.githubusercontent.com/1835170/166259908-2c3515e8-606c-4ae0-87d8-aa226637001c.png)

![image](https://user-images.githubusercontent.com/1835170/166259816-529e126d-b727-45d6-b68b-a908bcb43428.png)

**Comment by A-tG** [comment]
Updater rely on Github API. If it refuses to accept connection, download will fail. Also it is possible that program can't create folder where update will be downloaded. Try to move program to different folder (if its located in Program Files) or drive. Currently there is no logger so I cant tell what exactly gone wrong

**Comment by Glaived** [comment]
> Try to move program to different folder (if its located in Program Files)
FancyOSD is well located in the Program Files, sorry for the inconvenience.
