### ISSUE TITLE
Feature Request: Persistent mute icon

### ISSUE THREAD

**Issue by HenryBaby** [A-tG/VoicemeeterFancyOSD#18]
An option to set mute icon OSD as persistent, i.e no fadeout.

Edit: Could also apply to other OSD elements.

**Comment by A-tG** [comment]
Use option *AlwaysShowElements* in config.ini (fast access by pressing "Open Config File" in context menu of the tray icon)

**Comment by HenryBaby** [comment]
I saw this option, but I wasn't quite what I was looking for. Maybe there is no easy way to do this tho. I was thinking it would be nice if the mute element would stay on the screen for the duration of the mute. I.e. stay there until it's unmuted.

**Comment by HenryBaby** [comment]
@A-tG, could this be achieved by setting fadeout timer individually per OSD element in the config? I'm not asking you to do this, because it seems sub-optimized and not very user-oriented and frankly just plain ugly, but just curious if it could be possible.

**Comment by A-tG** [comment]
Every config option have to be implemented with some coding. I don't think this feature worth implementing.

**Comment by HenryBaby** [comment]
Yeah, I agree with you too. This is becoming my favourite tool since the last two days. Absolutely excellent.
