### ISSUE TITLE
Prevent a strip or a bus from showing its updates

### ISSUE THREAD

**Issue by VinceBT** [A-tG/VoicemeeterFancyOSD#2]
I have a macro button which is configured like this:
![image](https://user-images.githubusercontent.com/1362505/154588171-4ec1da3d-76d3-46a1-95a1-c68ff4f0514f.png)

It changes the gain of a strip depending on the sound of another strip, the problem is, when it happens, it shows the OSD, and it happens a lot, which is pretty distracting.
Is there a way to hide the OSD for this strip specifically ?

**Comment by A-tG** [comment]
It's not possible right now. I will add this feature in the future.

**Comment by A-tG** [comment]
Added in 0.9.9. I enhance it further in https://github.com/A-tG/VoicemeeterFancyOSD/issues/8
