### ISSUE TITLE
Feature Request: Add border size setting

### ISSUE THREAD

**Issue by HenryBaby** [A-tG/VoicemeeterFancyOSD#22]
Would it be possible to add an option to the config to change the border size, starting from 0 (where 0 means don't show it at all)?

**Comment by A-tG** [comment]
[0.12.2.0](https://github.com/A-tG/VoicemeeterFancyOSD/releases/tag/v0.12.2.0)

**Comment by HenryBaby** [comment]
Beautiful. Again, this is might be one of the best undiscovered applications out there :)
