### ISSUE TITLE
Suggestion: Repo link in the tray tool actions

### ISSUE THREAD

**Issue by VinceBT** [A-tG/VoicemeeterFancyOSD#27]
I think having a link to the repo and/or a link to report an issue could be great somewhere here:
![image](https://user-images.githubusercontent.com/1362505/170054116-21709c2b-b7d8-44a1-b62b-46c436d36cd9.png)

**Comment by A-tG** [comment]
I don't want to add too much stuff to the tray menu. There is at least *README.txt* in program's folder with the link to the github page.

When I will make UI/window with Settings there will be 'About' page for links, info, etc.
