### ISSUE TITLE
Display enumeration error

### ISSUE THREAD

**Issue by xcasxcursex** [A-tG/VoicemeeterFancyOSD#30]
Thanks for this very nice addition to the voicemeeter ecosystem :)

I've noticed one very small issue - I have dual displays here, and often use the secondary display only. This means that when I enable my primary display (read: turn on my other monitor), what was display '0' becomes display '1'. 

I always want the popup to appear on that secondary display (as the primary is for gaming exclusively) so I have FancyOSD configured to use display 1. 
When only the secondary is enabled, this fails gracefully and uses display 0, being the secondary monitor, and all is well. 
When both displays are enabled, this works as configured and uses display 1, being the secondary monitor, and all is well.
But If I start FancyOSD with only the one (secondary) monitor enabled, then enable the primary monitor, the monitor enumeration changes during FancyOSD's run time, and the OSD appears on my primary display, display 0, in spite of being configured to use display 1.

No big stress about this but if there's a performant way to deal with it, that'd be nice, so I thought I should report it.

**Comment by A-tG** [comment]
As far as I know Display enumeration works like that because of the OS. The program is designed to show OSD on available display event if settings, so probably when the primary display is disabled, the secondary display you mention in your case is 0 and when you connect primary - connected display becomes 1. I dont think I can fix that easily.

**Comment by xcasxcursex** [comment]
Sorry, I have neglected to mention an important detail, my workaround: After enabling/disabling a display, simply exit and restart FancyOSD, or, open the Settings and Info dialog and change the display number to something random and then back to the same number (1).

So, you're right about how windows is handling it, but the problem here is not that the displays are enumerated incorrectly when they are enumerated, it is that FancyOSD assumes that the enumeration has not changed since it was initialised. If, after enabling or disabling a monitor, I force it to re-enumerate the displays, everything works as expected.

So I guess, there would need to be a function to detect when display enumeration changes (ie: monitors are disabled/enabled), or to enumerate them before every OSD display (sounds expensive, I don't know though) or something like that.... I don't know how practical this kind of thing would be in reality, so, no pressure! I'm quietly hoping there's a windows API you can hook into on enumeration changes and it'll be really simple :)

**Comment by A-tG** [comment]
It's already keeping tracks of possible changes, but maybe display disconnection is not detected properly. Try this build and enable logger. Check what log file says when you disconnect/connect display. There will be something like
`` DEBUG DISPLAY ENUMERATION: Windows settings change detected - Desktop ``
[VoicemeeterFancyOsd-x64-1.0.0.1 disp enum test.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/9741474/VoicemeeterFancyOsd-x64-1.0.0.1.disp.enum.test.zip)

**Comment by A-tG** [comment]
I see it detects. It will help to investigate further if I have some problem in my code or in the library that enumerate displays.

**Comment by A-tG** [comment]
Try this version
[VoicemeeterFancyOsd-x64-1.0.0.1-preview.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/9743106/VoicemeeterFancyOsd-x64-1.0.0.1-preview.zip)

**Comment by xcasxcursex** [comment]
Works like a charm!  Thanks so much :)

There are no debug log messages in this one, I am guessing that's intentional, but I thought I should mention it.
