### ISSUE TITLE
WPF not working on Intel Iris graphics card

### ISSUE THREAD

**Issue by Melo-Professional** [A-tG/VoicemeeterFancyOSD#31]
I'll be posting here as reference and information to whom is facing issues trying to open VMFOSD Voicemeeter Fancy OSD.
It seems WPF (which VMFOSD relies on) using DirectX9 cannot run applications using new generations (11th / 12th gen) of Intel processors with Iris GPU (which does not support DX9 natively).
When you try to open VMFOSD through Intel GPU nothing happens.

Here are some usefull information about:
[https://community.intel.com/t5/Graphics/3D-rendering-issue-on-12th-gen-Intel-Core-i3/m-p/1407118/highlight/true#M109118](https://community.intel.com/t5/Graphics/3D-rendering-issue-on-12th-gen-Intel-Core-i3/m-p/1407118/highlight/true#M109118)
[https://community.intel.com/t5/Graphics/Graphics-failure-with-WPF-3D-content-and-Iris-XE/td-p/1415196](https://community.intel.com/t5/Graphics/Graphics-failure-with-WPF-3D-content-and-Iris-XE/td-p/1415196)
[https://github.com/microsoft/D3D9On12/issues/52](https://github.com/microsoft/D3D9On12/issues/52)
[https://github.com/dotnet/wpf/issues/7076](https://github.com/dotnet/wpf/issues/7076)

**Comment by A-tG** [comment]
Does program not starting at all? Or it's just UI is not displayed? If program is able to run I suggest to change/add ```RenderMode = SoftwareOnly``` under ```[Program]``` section in 
*PROGRAM_FOLDER/config/config.ini*.

**Comment by Melo-Professional** [comment]
> Does program not starting at all? Or it just UI is not displayed? If program is able to run I suggest to change `RenderMode = Default` to `RenderMode = SoftwareOnly` under `[Program]` section in _PROGRAM_FOLDER/config/config.ini_

It doesn't start. It just gets killed. Even using RenderMode to SoftwareOnly.

**Comment by A-tG** [comment]
Try to disable hardware acceleration globally https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/graphics-rendering-registry-settings?view=netframeworkdesktop-4.8#disable-hardware-acceleration-option
The problem is that the RenderMode is changed at runtime. If It doesn't even start I'm not sure If I can make any workarounds. If disabling hardware acceleration helps, then maybe I can make the program use SoftwareOnly in the beginning of runtime and then switch to correct mode according to config.
Have you tried both VoicemeeterFancyOsd.exe and VoicemeeterFancyOsdHost.exe?

**Comment by Melo-Professional** [comment]
> Try to disable hardware acceleration globally https://learn.microsoft.com/en-us/dotnet/desktop/wpf/graphics-multimedia/graphics-rendering-registry-settings?view=netframeworkdesktop-4.8#disable-hardware-acceleration-option The problem is that the RenderMode is changed at runtime. If It doesn't even start I'm not sure If I can make any workarounds. If disabling hardware acceleration helps, then maybe I can make the program use SoftwareOnly in the beginning of runtime and then switch to correct mode according to config. Have you tried both VoicemeeterFancyOsd.exe and VoicemeeterFancyOsdHost.exe?

I did try the register to disable hardware acceleration. Doesn't work.
I have tried both .exe... still nothing.

It only works IF I do this:
1 - Windows Settings / System / Display / Graphics / add VoicemeeterFancyOsd.exe and VoicemeeterFancyOsdHost.exe to use NVIDIA RTX 3050;
2 - Windows Settings / System / Display / disable the notebook internal display (which is handled by Intel Iris);
3 - Windows Settings / System / Display / use external display from HDMI port (which uses NVIDIA RTX 3050).

But I need both display monitors for my daily use...

**Comment by Melo-Professional** [comment]
Maybe you could try this at code level:
[https://community.intel.com/t5/Graphics/Graphics-failure-with-WPF-3D-content-and-Iris-XE/m-p/1417581/highlight/true#M110056](https://community.intel.com/t5/Graphics/Graphics-failure-with-WPF-3D-content-and-Iris-XE/m-p/1417581/highlight/true#M110056)

"...
Until a permanent solution from Intel or Microsoft arrives, I can suggest the following workarounds:

Solution in code:
Enter the following setting in the xaml code of your Window:
RenderOptions.EdgeMode="Aliased"
..."

I have try the others suggestions from there.

**Comment by Melo-Professional** [comment]
More reference from ModernFlyouts:
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1066
https://github.com/ModernFlyouts-Community/ModernFlyouts/issues/1060

**Comment by A-tG** [comment]
[VoicemeeterFancyOsd-x64-1.0.0.2 iGPU-workaround.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10128806/VoicemeeterFancyOsd-x64-1.0.0.2.iGPU-workaround.zip)
This is version with "Aliased" option. If it works I will need to implement option in main branch.

**Comment by Melo-Professional** [comment]
> [VoicemeeterFancyOsd-x64-1.0.0.2 iGPU-workaround.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10128806/VoicemeeterFancyOsd-x64-1.0.0.2.iGPU-workaround.zip) This is version with "Aliased" option. If it works I will need to implement option in main branch.

Didn't work.... 
I'd trying bothe .exe, try change config rendermode to softwareonly, even try to turn off windows defender.
Still nothing...
Anyway, thanks for that, I really,really appreciate it.

**Comment by A-tG** [comment]
This version should display several dialogs windows while program initialization:
* Program start
* WPF thread start
* WPF startup
* WPF startup finished
If none are displayed then I assume Microsoft broke something in .NET/WPF/Windows
[VoicemeeterFancyOsd-x64-1.0.0.2 DEBUG.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10146830/VoicemeeterFancyOsd-x64-1.0.0.2.DEBUG.zip)

**Comment by Melo-Professional** [comment]
> 
Hey buddy, thanks for keep trying.
Running this version, this is what I got:

Program start
WPF thread start
WPF startup

After that, the program is killed, vanished, disapears.

**Comment by A-tG** [comment]
[VoicemeeterFancyOsd-x64-1.0.0.2 DEBUG2.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10147294/VoicemeeterFancyOsd-x64-1.0.0.2.DEBUG2.zip)
There a gonna be other dialogs now.

**Comment by Melo-Professional** [comment]
> [VoicemeeterFancyOsd-x64-1.0.0.2 DEBUG2.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10147294/VoicemeeterFancyOsd-x64-1.0.0.2.DEBUG2.zip) There a gonna be other dialogs now. Try to check both normal exe and *Host.exe


This is what I got:
WPF startup
DPI helper init
Tray icon init

And it's gone.
Did try both exe files as usual.

**Comment by A-tG** [comment]
This is very unexpected. If there is problem with Tray Icon it will be hard to fix because it relies on 3rd party dll. 
[VoicemeeterFancyOsd-x64-1.0.0.2 DEBUG3.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10147475/VoicemeeterFancyOsd-x64-1.0.0.2.DEBUG3.zip)
Try this, most likely there will be no tray icon and you will need to kill the program manually

**Comment by Melo-Professional** [comment]
> This is very unexpected. If there is problem with Tray Icon it will be hard to fix because it relies on 3rd party dll. [VoicemeeterFancyOsd-x64-1.0.0.2 DEBUG3.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10147475/VoicemeeterFancyOsd-x64-1.0.0.2.DEBUG3.zip) Try this, most likely there will be no tray icon and you will need to kill the program manually

Cool. 
Yep, no trayicon.
I didn't need to force close the program from Task Manager.

This is what appears:
Tray icon init
TrayIcon InitializeComponent

and the process is over.

**Comment by A-tG** [comment]
[VoicemeeterFancyOsd-x64-1.0.0.2 replaced tray lib.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10179215/VoicemeeterFancyOsd-x64-1.0.0.2.replaced.tray.lib.zip)
I found replacement for Tray icon library, check if this version working.

**Comment by Melo-Professional** [comment]
> [VoicemeeterFancyOsd-x64-1.0.0.2 replaced tray lib.zip](https://github.com/A-tG/VoicemeeterFancyOSD/files/10179215/VoicemeeterFancyOsd-x64-1.0.0.2.replaced.tray.lib.zip) I found replacement for Tray icon library, check if this version working.

Sorry for late response.
I did run this one, both .exe, nothing shows, nothing seems to happen...
Thanks for keep trying, you are great!

**Comment by Squall-Leonhart** [comment]
use the [Arc/Iris Xe](https://www.intel.com/content/www/us/en/download/726609/intel-arc-iris-xe-graphics-whql-windows.html) driver instead of the [DCH](https://www.intel.com.au/content/www/au/en/download/19344/intel-graphics-windows-dch-drivers.html) driver.

**Comment by Melo-Professional** [comment]
Hey @A-tG is working now with current version. Also I did what you say here: https://github.com/A-tG/VoicemeeterFancyOSD/issues/34#issuecomment-1634445827
I'm very happy to be able to use it again, after so many months!
Thanks dude
