### ISSUE TITLE
Multi monitor support?

### ISSUE THREAD

**Issue by Zo-Bro-23** [A-tG/VoicemeeterFancyOSD#4]
Currently, the ```config.ini``` file has an option to show the monitor display index (which is great btw), but is there a way to show it on multiple monitors or _**all**_ monitors? Sometimes I'm only paying attention to one monitor, so I would like to just have it show on both my monitors. Would you be able to add this feature?

**Comment by A-tG** [comment]
It will be too much trouble to implement. The closest feature to this will be - "to show OSD on another display if any app specified in the config file is running" - the feature that will be added in upcoming release.

**Comment by Dragonisser** [comment]
Why is that too much trouble?
